### ISSUE TITLE
PrettyPlots version confliction

### ISSUE THREAD

**Issue by YifanWeng** [JuliaMPC/PrettyPlots.jl#2]
When I Used the command
`Pkg.add("NLOptControl")` to install the package, there is an error   

> julia> Pkg.add("NLOptControl")
ERROR: fixed packages introduce conflicting requirements for NLOptControl:
         PrettyPlots requires versions [0.1.5+,∞) [none of the available versions can satisfy this r
equirement]
       available versions are 0.1.2, 0.1.3, 0.1.4 and 0.1.5
check_requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.P
kg.Types.Available}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\query.jl:222
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{Str
ing,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:496
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\e
ntry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where
N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
Stacktrace:
 [1] sync_end() at .\task.jl:287
 [2] macro expansion at .\task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl
:59
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at .\pkg\di
r.jl:36
 [7] add(::String) at .\pkg\pkg.jl:117, 

which stops the installation process.

**Comment by huckl3b3rry87** [comment]
I think that you must have already done
```
Pkg.add("PrettyPlots")
Pkg.checkout("PrettyPlots")
```
Which will put you on the [master branch](https://github.com/JuliaMPC/PrettyPlots.jl/blob/master/REQUIRE) not the[ tagged branch ](https://github.com/JuliaMPC/PrettyPlots.jl/blob/v0.0.1/REQUIRE)

**Option A**
If you want to run the stable tagged branch then try
```
Pkg.pin("PrettyPlots",v"0.0.1")
```
Then do 
```
Pkg.add("NLOptControl")
Pkg.pin("NLOptControl",v"0.1.3")
```
Assuming that you also want VehicleModels.jl
```
Pkg.add("VehicleModels")
Pkg.pin("VehicleModels",v"0.1.3")
```
This option is nice because the [documentation ](https://juliampc.github.io/MPCDocs.jl/v0.1.3/index.html)is up to date

**Option B**
I am assuming (knowing you...) that you want to run simulations with vehicle control. In this case, you should use [MAVs.jl](https://github.com/JuliaMPC/MAVs.jl).

The only drawback to this option is that I am not quite yet ready to tag everything, so you need to work on the master branch which is not fully documented, but the .travis tests are passing. 

Look at the above link to install the entire software stack. 

Then to get PrettyPlots.jl as well:
```
Pkg.add("PrettyPlots")
Pkg.checkout("PrettyPlots")
```

**Comment by huckl3b3rry87** [comment]
@YifanWeng please let me know if this works

**Comment by YifanWeng** [comment]
I tried both options and both of them work very well. Option A is great for only using NLOptControl if the stable version is desired (should follow the comment step by step and the problem should be solved). Option B is great for vehicle control package MAVs. As you stated, the only tiny flaw is the unlabeled package, which is totally acceptable. The help is extremely helpful for installing the packages. Thanks!
